spag.py
Should allow you to do both ./spag.py and just `spag` if it's pip installed.
=> Fix broken install

spag.py
spag show - gets endpoint
spag set - sets endpoint
spag clear- clears endpoint
=> Set, show, clear commands, a bit more Click-y

requirements.txt
This fixes compatibility with python3 and pypy
=> Remove unnecessary requirement to fix python3 compatability

spag.py, tests/test_spag.py, tests/testapp.py
Add headers and make GET code better
=> Add HTTP header support, and make GET better.

common.py, setup.py, spag.py, spag_files.py, tests/resources/auth.yml, tests/resources/delete_thing.yml, tests/resources/headers.yml, tests/resources/v2/patch_thing.yml, tests/resources/v2/post_thing.yml, tests/test_spag.py
* Define requests in yaml files
* Spag discovers request files in specified directories
* Added spag request command
* `spag request post_thing.yml --dir=./tests/resources`
* `spag request v2/post_thing.yml --dir=./tests/resources`
- looks first for 'post_thing.yml' in our dir
- uses 'v2/post_thing.yml' to disambiguate
* common.py resolves a circular dependency between spag and spag_files
=> Spag request from a predefined file

decorators.py, setup.py, spag.py
Moves the decorators to their own file
=> Move decorators to their own file

spag_files.py
=> Fix bad error message on bad requests directory

spag_files.py, tests/test_spag.py
=> Sorted output of `spag requests --show`

spag.py, spag_remembers.py, tests/test_spag.py
* `spag history` lists previous requests
* `spag history show <index>` shows a specific request from your history
=> Add a `spag history` command

README.md
* Document environments, templates, history, remembers, contributing
* Add some todo
=> First pass at improving documentation

Cargo.toml, src/spag/env.rs, src/spag/main.rs, src/spag/request.rs, src/spag/test.rs, tests/test_spag.py
=> spag env unset

src/spag/env.rs, src/spag/main.rs, src/spag/request.rs, tests/test_spag.py
=> Multiple Environments

Cargo.toml, src/spag/env.rs, src/spag/main.rs, src/spag/mod.rs, src/spag/template.rs, src/spag/test.rs
=> Templates for spag-rs

src/lib.rs, src/spag/env.rs, src/spag/file.rs, src/spag/main.rs, src/spag/request.rs, tests/test_spag.py
Probably templates will happen in a separate pull request
=> Add spag request

src/spag/env.rs, src/spag/file.rs, src/spag/history.rs, src/spag/main.rs, src/spag/mod.rs, src/spag/request.rs, tests/test_spag.py
=> Spag rs history

src/spag/file.rs, src/spag/main.rs, src/spag/template.rs, tests/test_spag.py
=> Make templates work

src/lib.rs, src/spag/args.rs, src/spag/env.rs, src/spag/file.rs, src/spag/history.rs, src/spag/main.rs, src/spag/mod.rs, src/spag/request.rs, src/spag/template.rs, src/spag/test.rs, src/spag/yaml_util.rs
* Puts argument-related stuff in `args.rs`
* Puts yaml-related stuff in `yaml_util.rs`
* Adds `dump_yaml_file` to write out a yaml file
* Removes of unwraps and panics
=> Refactor some things

src/spag/history.rs, src/spag/main.rs, src/spag/mod.rs, src/spag/remember.rs, src/spag/template.rs, src/spag/test.rs, tests/test_spag.py
=> Remember the last request

src/spag/env.rs, src/spag/history.rs, src/spag/main.rs, tests/test_spag.py
- Don't panic when activating non-existent environment
- Dont panic on missing .spag directory
=> Small fixes

tests/test_spag.py, tests/testapp.py
- New endpoint in the testapp
- Adds a few tests to verify that request parameters work
=> Add tests for URL parameters
